// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex_multiple from "./islands/AddToCartButton/vtex-multiple.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $AddToCartComponents from "./islands/AddToCartComponents.tsx";
import * as $Analytics from "./islands/Analytics.tsx";
import * as $BannerStopWatch from "./islands/BannerStopWatch.tsx";
import * as $BuyTogetherSelectButton from "./islands/BuyTogetherSelectButton.tsx";
import * as $BuyTogetherTotal from "./islands/BuyTogetherTotal.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_GeoLocationPointBar_GeoLocationPoint from "./islands/Header/GeoLocationPointBar/GeoLocationPoint.tsx";
import * as $Header_GeoLocationPointBar_GeoLocationPointBar from "./islands/Header/GeoLocationPointBar/GeoLocationPointBar.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $ImageZoom from "./islands/ImageZoom.tsx";
import * as $Installments from "./islands/Installments.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OursStores from "./islands/OursStores.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductGalleryIsland from "./islands/ProductGalleryIsland.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductShelfTimedOffers from "./islands/ProductShelfTimedOffers.tsx";
import * as $ProductVisualization from "./islands/ProductVisualization.tsx";
import * as $RangePrice from "./islands/RangePrice.tsx";
import * as $ReviewsList from "./islands/ReviewsList.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Toast_Toast from "./islands/Toast/Toast.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex-multiple.tsx":
      $AddToCartButton_vtex_multiple,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/AddToCartComponents.tsx": $AddToCartComponents,
    "./islands/Analytics.tsx": $Analytics,
    "./islands/BannerStopWatch.tsx": $BannerStopWatch,
    "./islands/BuyTogetherSelectButton.tsx": $BuyTogetherSelectButton,
    "./islands/BuyTogetherTotal.tsx": $BuyTogetherTotal,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/GeoLocationPointBar/GeoLocationPoint.tsx":
      $Header_GeoLocationPointBar_GeoLocationPoint,
    "./islands/Header/GeoLocationPointBar/GeoLocationPointBar.tsx":
      $Header_GeoLocationPointBar_GeoLocationPointBar,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/ImageZoom.tsx": $ImageZoom,
    "./islands/Installments.tsx": $Installments,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OursStores.tsx": $OursStores,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductGalleryIsland.tsx": $ProductGalleryIsland,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductShelfTimedOffers.tsx": $ProductShelfTimedOffers,
    "./islands/ProductVisualization.tsx": $ProductVisualization,
    "./islands/RangePrice.tsx": $RangePrice,
    "./islands/ReviewsList.tsx": $ReviewsList,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Toast/Toast.tsx": $Toast_Toast,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
