// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$7 from "./loaders/newslettter.ts";
import * as $$$8 from "./loaders/product/buyTogether.ts";
import * as $$$9 from "./loaders/reviews/productReviews.ts";
import * as $$$10 from "./loaders/search/intelligenseSearch.ts";
import * as $$$2 from "./loaders/Wishlist/add-wishlist-item.ts";
import * as $$$3 from "./loaders/Wishlist/create-wishlist.ts";
import * as $$$4 from "./loaders/Wishlist/get-wishlist-items.ts";
import * as $$$5 from "./loaders/Wishlist/get-wishlist-list.ts";
import * as $$$6 from "./loaders/Wishlist/remove-wishlist-item.ts";
import * as $$$$$$0 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$2 from "./sections/Content/Benefits.tsx";
import * as $$$$$$3 from "./sections/Content/Faq.tsx";
import * as $$$$$$4 from "./sections/Content/Logos.tsx";
import * as $$$$$$5 from "./sections/Content/SimpleText.tsx";
import * as $$$$$$6 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$7 from "./sections/Departament/DepartamentList.tsx";
import * as $$$$$$8 from "./sections/Footer/Footer.tsx";
import * as $$$$$$9 from "./sections/Gallery.tsx";
import * as $$$$$$10 from "./sections/Header/Header.tsx";
import * as $$$$$$11 from "./sections/HiddenContentLogin/HiddenContentLogin.tsx";
import * as $$$$$$12 from "./sections/Images/BannerIsland.tsx";
import * as $$$$$$13 from "./sections/Images/BannersGrid.tsx";
import * as $$$$$$14 from "./sections/Images/Carousel.tsx";
import * as $$$$$$15 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$16 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$17 from "./sections/Layout/Container.tsx";
import * as $$$$$$18 from "./sections/Layout/Flex.tsx";
import * as $$$$$$19 from "./sections/Layout/Grid.tsx";
import * as $$$$$$20 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$21 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$22 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$23 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$24 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$25 from "./sections/MostSearchedProducts/MostSearchedProducts.tsx";
import * as $$$$$$26 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$27 from "./sections/Product/BuyTogether.tsx";
import * as $$$$$$28 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$29 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$30 from "./sections/Product/MountedPDP.tsx";
import * as $$$$$$31 from "./sections/Product/NotFound.tsx";
import * as $$$$$$32 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$33 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$34 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$35 from "./sections/Product/ProductReviews.tsx";
import * as $$$$$$36 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$37 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$38 from "./sections/Product/ProductShelfTimedOffers.tsx";
import * as $$$$$$39 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$40 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$41 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$42 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$43 from "./sections/Theme/Theme.tsx";
import * as $$$$$$44 from "./sections/UtilLinks/UtilLinks.tsx";

const manifest = {
  "loaders": {
    "deco-sites/casaevideo/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/casaevideo/loaders/List/Sections.tsx": $$$1,
    "deco-sites/casaevideo/loaders/newslettter.ts": $$$7,
    "deco-sites/casaevideo/loaders/product/buyTogether.ts": $$$8,
    "deco-sites/casaevideo/loaders/reviews/productReviews.ts": $$$9,
    "deco-sites/casaevideo/loaders/search/intelligenseSearch.ts": $$$10,
    "deco-sites/casaevideo/loaders/Wishlist/add-wishlist-item.ts": $$$2,
    "deco-sites/casaevideo/loaders/Wishlist/create-wishlist.ts": $$$3,
    "deco-sites/casaevideo/loaders/Wishlist/get-wishlist-items.ts": $$$4,
    "deco-sites/casaevideo/loaders/Wishlist/get-wishlist-list.ts": $$$5,
    "deco-sites/casaevideo/loaders/Wishlist/remove-wishlist-item.ts": $$$6,
  },
  "sections": {
    "deco-sites/casaevideo/sections/Category/CategoryBanner.tsx": $$$$$$0,
    "deco-sites/casaevideo/sections/Category/CategoryList.tsx": $$$$$$1,
    "deco-sites/casaevideo/sections/Content/Benefits.tsx": $$$$$$2,
    "deco-sites/casaevideo/sections/Content/Faq.tsx": $$$$$$3,
    "deco-sites/casaevideo/sections/Content/Logos.tsx": $$$$$$4,
    "deco-sites/casaevideo/sections/Content/SimpleText.tsx": $$$$$$5,
    "deco-sites/casaevideo/sections/Content/Testimonials.tsx": $$$$$$6,
    "deco-sites/casaevideo/sections/Departament/DepartamentList.tsx": $$$$$$7,
    "deco-sites/casaevideo/sections/Footer/Footer.tsx": $$$$$$8,
    "deco-sites/casaevideo/sections/Gallery.tsx": $$$$$$9,
    "deco-sites/casaevideo/sections/Header/Header.tsx": $$$$$$10,
    "deco-sites/casaevideo/sections/HiddenContentLogin/HiddenContentLogin.tsx":
      $$$$$$11,
    "deco-sites/casaevideo/sections/Images/BannerIsland.tsx": $$$$$$12,
    "deco-sites/casaevideo/sections/Images/BannersGrid.tsx": $$$$$$13,
    "deco-sites/casaevideo/sections/Images/Carousel.tsx": $$$$$$14,
    "deco-sites/casaevideo/sections/Images/ImageGallery.tsx": $$$$$$15,
    "deco-sites/casaevideo/sections/Images/ShoppableBanner.tsx": $$$$$$16,
    "deco-sites/casaevideo/sections/Layout/Container.tsx": $$$$$$17,
    "deco-sites/casaevideo/sections/Layout/Flex.tsx": $$$$$$18,
    "deco-sites/casaevideo/sections/Layout/Grid.tsx": $$$$$$19,
    "deco-sites/casaevideo/sections/Layout/GridItem.tsx": $$$$$$20,
    "deco-sites/casaevideo/sections/Links/LinkTree.tsx": $$$$$$21,
    "deco-sites/casaevideo/sections/Links/Shortcuts.tsx": $$$$$$22,
    "deco-sites/casaevideo/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$23,
    "deco-sites/casaevideo/sections/Miscellaneous/CookieConsent.tsx": $$$$$$24,
    "deco-sites/casaevideo/sections/MostSearchedProducts/MostSearchedProducts.tsx":
      $$$$$$25,
    "deco-sites/casaevideo/sections/Newsletter/Newsletter.tsx": $$$$$$26,
    "deco-sites/casaevideo/sections/Product/BuyTogether.tsx": $$$$$$27,
    "deco-sites/casaevideo/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$28,
    "deco-sites/casaevideo/sections/Product/ImageGallerySlider.tsx": $$$$$$29,
    "deco-sites/casaevideo/sections/Product/MountedPDP.tsx": $$$$$$30,
    "deco-sites/casaevideo/sections/Product/NotFound.tsx": $$$$$$31,
    "deco-sites/casaevideo/sections/Product/NotFoundChallenge.tsx": $$$$$$32,
    "deco-sites/casaevideo/sections/Product/ProductDescription.tsx": $$$$$$33,
    "deco-sites/casaevideo/sections/Product/ProductInfo.tsx": $$$$$$34,
    "deco-sites/casaevideo/sections/Product/ProductReviews.tsx": $$$$$$35,
    "deco-sites/casaevideo/sections/Product/ProductShelf.tsx": $$$$$$36,
    "deco-sites/casaevideo/sections/Product/ProductShelfTabbed.tsx": $$$$$$37,
    "deco-sites/casaevideo/sections/Product/ProductShelfTimedOffers.tsx":
      $$$$$$38,
    "deco-sites/casaevideo/sections/Product/SearchResult.tsx": $$$$$$39,
    "deco-sites/casaevideo/sections/Product/Wishlist.tsx": $$$$$$40,
    "deco-sites/casaevideo/sections/Social/InstagramPosts.tsx": $$$$$$41,
    "deco-sites/casaevideo/sections/Social/WhatsApp.tsx": $$$$$$42,
    "deco-sites/casaevideo/sections/Theme/Theme.tsx": $$$$$$43,
    "deco-sites/casaevideo/sections/UtilLinks/UtilLinks.tsx": $$$$$$44,
  },
  "apps": {
    "deco-sites/casaevideo/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/casaevideo/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/casaevideo",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
