import daisyui from "daisyui";

export default {
  plugins: [daisyui],
  daisyui: {
    themes: [{
      light: {
        "--brand-primary-1": "#740F02",
        "--brand-primary-900": "#740F02",
        "--brand-primary-800": "white",
        "--brand-primary-700": "white",
        "--brand-primary-600": "white",
        "--brand-primary-500": "white",
        "--brand-primary-400": "white",
        "--brand-primary-300": "white",
        "--brand-primary-200": "white",
        "--brand-primary-100": "white",
        "--brand-primary-50": "white",
        "--brand-secondary-1": "white",
        "--brand-secondary-900": "white",
        "--brand-secondary-800": "white",
        "--brand-secondary-700": "white",
        "--brand-secondary-600": "white",
        "--brand-secondary-500": "white",
        "--brand-secondary-400": "white",
        "--brand-secondary-300": "white",
        "--brand-secondary-200": "white",
        "--brand-secondary-100": "white",
        "--brand-secondary-50": "white",

        "--neutral-1": "white",
        "--neutral-900": "white",
        "--neutral-800": "white",
        "--neutral-700": "white",
        "--neutral-600": "white",
        "--neutral-500": "white",
        "--neutral-400": "white",
        "--neutral-300": "white",
        "--neutral-200": "white",
        "--neutral-100": "white",
        "--neutral-50": "white",
        "--brand-terciary-1": "white",
        "--complementary-1": "white",
        "--complementary-2": "white",
        "--complementary-3": "white",
        "--complementary-4": "white",
        "--success-light": "white",
        "--information": "white",
        "--information-light": "white",
        "--warning": "white",
        "--warning-light": "white",
        "--warning-dark": "white",
        "--error-light": "white",
      },
    }],
    logs: false,
  },
  content: ["./**/*.tsx"],
  theme: {
    container: { center: true },
    colors: {
      "brand-primary-1": "oklch(var(--brand-primary-1))",
      "brand-primary-900": "oklch(var(--brand-primary-900))",
      "brand-primary-800": "oklch(var(--brand-primary-800))",
      "brand-primary-700": "oklch(var(--brand-primary-700))",
      "brand-primary-600": "oklch(var(--brand-primary-600))",
      "brand-primary-500": "oklch(var(--brand-primary-500))",
      "brand-primary-400": "oklch(var(--brand-primary-400))",
      "brand-primary-300": "oklch(var(--brand-primary-300))",
      "brand-primary-200": "oklch(var(--brand-primary-200))",
      "brand-primary-100": "oklch(var(--brand-primary-100))",
      "brand-primary-50": "oklch(var(--brand-primary-50))",
      "brand-secondary-900": "oklch(var(--brand-secondary-900))",
      "brand-secondary-800": "oklch(var(--brand-secondary-800))",
      "brand-secondary-700": "oklch(var(--brand-secondary-700))",
      "brand-secondary-600": "oklch(var(--brand-secondary-600))",
      "brand-secondary-500": "oklch(var(--brand-secondary-500))",
      "brand-secondary-400": "oklch(var(--brand-secondary-400))",
      "brand-secondary-300": "oklch(var(--brand-secondary-300))",
      "brand-secondary-200": "oklch(var(--brand-secondary-200))",
      "brand-secondary-100": "oklch(var(--brand-secondary-100))",
      "brand-secondary-50": "oklch(var(--brand-secondary-50))",
      "brand-secondary-1": "oklch(var(--brand-secondary-1))",
      neutral: {
        900: "oklch(var(--neutral-900))",
      },
      "neutral-800": "oklch(var(--neutral-800))",
      "neutral-700": "oklch(var(--neutral-700))",
      "neutral-600": "oklch(var(--neutral-600))",
      "neutral-500": "oklch(var(--neutral-500))",
      "neutral-400": "oklch(var(--neutral-400))",
      "neutral-300": "oklch(var(--neutral-300))",
      "neutral-200": "oklch(var(--neutral-200))",
      "neutral-100": "oklch(var(--neutral-100))",
      "neutral-50": "oklch(var(--neutral-50))",
      "neutral-1": "oklch(var(--neutral-1))",
      "brand-terciary-1": "oklch(var(--brand-terciary-1))",
      "complementary-1": "oklch(var(--complementary-1))",
      "complementary-2": "oklch(var(--complementary-2))",
      "complementary-3": "oklch(var(--complementary-3))",
      "complementary-4": "oklch(var(--complementary-4))",
      "success-light": "oklch(var(--success-light))",
      "information": "oklch(var(--information))",
      "information-light": "oklch(var(--information-light))",
      "warning": "oklch(var(--warning))",
      "warning-light": "oklch(var(--warning-light))",
      "warning-dark": "oklch(var(--warning-dark))",
      "error-light": "oklch(var(--error-light))",
      "black": "black",
    },
  },
};
